arb-dir: lib/app/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: lib/app/generated
output-class: AppLocalizations
use-escaping: true
nullable-getter: false
synthetic-package: false
